spring.application.name=mySpringAi_MCP_Server_streamhttp_remote
# 設定 MCP Server 對外宣告的名稱，client 初始化連線時可用來辨識這台 server；預設名稱是 mcp-server。
spring.ai.mcp.server.name=mySpringAi_MCP_Server_streamhttp_remote
################ Log 相關設定 ################
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
################ H2 Database 相關設定 ################
# AUTO_SERVER=true 多個連線同時存取同一個 H2 檔案 Spring Boot app + H2 Console + DataGrip
spring.datasource.url=jdbc:h2:file:./h2db/mcpserver_streamhttp_remote;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# 啟用 H2 Console
spring.h2.console.enabled=true
################ JPA/Hibernate 相關設定 ################
# Hibernate 啟動時根據 JPA Entity 嘗試更新資料表結構；通常會保留既有資料，但不適合取代正式 migration。
spring.jpa.hibernate.ddl-auto=update
################ MCP Server streamable HTTP remote 相關設定 ################
# 這個應用程式要以 Servlet 型態啟動，也就是使用傳統 Spring MVC 的 Web 應用模式。
spring.main.web-application-type=servlet
server.port=8081
# 我的 MCP Server 要用 Streamable HTTP 模式作為 MCP 通訊模式，對外提供服務。
# treamable 的好處是讓 MCP Server 變成更適合遠端 HTTP 部署、長時間任務、多段訊息回傳的通訊模式，而不是只適合一次請求、一次回應的簡單工具
# 多 client / 遠端共用，選 STREAMABLE；本機單一 client 啟動工具，選 STDIO。
spring.ai.mcp.server.protocol=streamable
# npx @modelcontextprotocol/inspector
# Transport Type: Streamable HTTP
# URL: http://localhost:8081/mcp

